### ISSUE TITLE
update the AguaClara google map

### ISSUE THREAD

**Issue by monroews** [AguaClara/public_relations#1]
Here is the [google map](https://www.google.com/maps/@14.2400899,-88.0213633,8z/data=!4m2!6m1!1s1Rjl2cfjMn0Pk7E11KVq9A1mlj2Q). 

Add 
Agua Para el Pueblo headquarters in Tegucigalpa
Agua Para La Vida headquarters in Nicaragua
La PODA plant (San Rafael del Norte) in Nicargua

Make sure all plants have photos and key data (like flow rates)

**Comment by swimhelenhsu** [comment]
Would this be something wkm works on?
