### ISSUE TITLE
Sell 12 Rotary Dinner Raffle Tickets

### ISSUE THREAD

**Issue by isakaminsky** [AguaClara/public_relations#19]

**Comment by yyr2** [comment]
"Hi (name),

 I wanted to let you know about a nice opportunity.  I'm emailing those who might be interested in supporting global water through AguaClara Reach (one of my two main volunteer gigs aguaclarareach.org)  while also getting a chance to win special dinners at the best local restaurants, in the Dozen Dinner Draw sponsored by Rotary:  http://rotarydozendinnerdraw.org/

I have ten $50 tickets to sell in the next 10 days, so let me know if you are interested!

Thanks,
John"

**Comment by ashleyhe16** [comment]
3 tickets sold

**Comment by mac545** [comment]
sold 2 :)))

**Comment by yyr2** [comment]
Ashley Sold 2
Michele Sold 2
Yitzy Sold 2
Anishka Sold 1
Rachel Sold 1
