### ISSUE TITLE
AguaClara Calendar

### ISSUE THREAD

**Issue by monroews** [AguaClara/public_relations#2]
Considering publishing an AguaClara calendar with a photo of a plant for every month.

**Comment by swimhelenhsu** [comment]
Would we have funding for this?

**Comment by monroews** [comment]
Is there a way to do this using an online calendar printer that wouldn't require us to front any money? 

I'd recommend exploring for 15 minutes and then if it doesn't look attractive close this issue and if it does look attractive then keep this task alive.
