### ISSUE TITLE
Add OSU peeps to Slack

### ISSUE THREAD

**Issue by yyr2** [AguaClara/public_relations#29]
Hey JuRoMa,

Could you please add the following email addresses to our slack? I'll reopen the issue as more OSU peeps create accounts.

bernard.204@buckeyemail.osu.edu

Thank you!!!

**Comment by JustinConneely** [comment]
Just sent the invite!

**Comment by yyr2** [comment]
reese.2181@osu.edu
ulatowski.4@osu.edu
travis.137@buckeyemail.osu.edu
